services:
  multi-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "38291:38291"
    volumes:
      - ./output/AP_70916155868361649699.archipelago:/archipelago.archipelago
  minecraft-1:
    build:
      context: .
      dockerfile: Dockerfile-minecraft
    environment:
      HOST: server
      EULA: true
    ports:
      - "25565:25565"
    volumes:
      - ./output/AP_70916155868361649699_P1_minecraft-1.apmc:/minecraft.apmc
  minecraft-2:
    build:
      context: .
      dockerfile: Dockerfile-minecraft
    environment:
      HOST: server
      EULA: true
    ports:
      - "25566:25565"
    volumes:
      - ./output/AP_70916155868361649699_P2_minecraft-2.apmc:/minecraft.apmc
  factorio-1:
    build:
      context: .
      dockerfile: Dockerfile-factorio
    ports:
      - "34197:34197/udp"
    volumes:
      - ./output/AP-70916155868361649699-P3-noa-factorio_0.5.0.zip:/archipelago/factorio/mods/AP-70916155868361649699-P3-noa-factorio_0.5.0.zip
