ACHIEVEMENT_ROW_COUNT: int = 18
ACHIEVEMENTS: list[list[str]] = [
    [
        "You gotta start somewhere",
        "100 antimatter is a lot",
        "Half Life 3 CONFIRMED",
        "L4D: Left 4 Dimensions",
        "5 Dimensions Antimatter Punch",
        "We couldn't afford 9",
        "Not a luck related achievement",
        "90 degrees to infinity",
    ],
    [
        "to infinity!",
        "FAKE NEWS!",
        "The 9th Dimension is a lie",
        "Antimatter Apocalypse",
        "Boosting to the max",
        "You got past the Big Wall",
        "Double Galaxy",
        "There's no point in doing that...",
    ],
    [
        "I forgot to nerf that",
        "The Gods are pleased",
        "That's a lot of infinites",
        "You didn't need it anyway",
        "Don't you dare sleep",
        "Claustrophobic",
        "That's FAST!",
        "I don't believe in Gods",
    ],
    [
        "NO DLC Required",
        "Super Sanic",
        "How the antitables have turned...",
        "Over in 30 Seconds",
        "Faster than a potato",
        "Multidimesional",
        "Daredevil",
        "AntiChallanged",
    ],
    [
        "Limit Break",
        "Age of Automation",
        "Definitely not worth it",
        "That's FASTER!",
        "Forever isn't that long",
        "Many Deaths",
        "Gift from the Gods",
        "This is fine.",
    ],
    [
        "Bulked up",
        "Oh, hey... You're still here?",
        "A new beginning",
        "Zero Deaths",
        "Not-so-challenging",
        "Faster than a squared potato",
        "Infinitely Challenging",
        "You did this again just for the achievement right?",
    ],
    [
        "ERROR 909: Dimension not found",
        "Can't hold all these infinities",
        "THIS ACHIEVEMENT DOESN'T EXIST",
        "Not a second lost",
        "NEW DIMENSIONS???",
        "One for each dimension",
        "1 Million is a lot",
        "Blink of an eye",
    ],
    [
        "Game Design Is My Passion",
        "Anti-antichallenged",
        "YOU CAN GET 50 GALAXIES?!?!",
        "I got a few to spare",
        "ALL YOUR IP ARE BELONG TO US",
        "Do you even bend time bro?",
        "2 MILLION INFINITIES",
        "Yet another infinity reference",
    ],
    [
        "Ludicrous Speed",
        "I brake for NOBODY!",
        "MAXIMUM OVERDRIVE",
        "4.3333 minutes of Infinity",
        "Is this safe?",
        "Time is relative",
        "Like jumping on a lego",
        "0 degrees from Infinity",
    ],
    [
        "8 nobody got time for that",
        "This mile took an eternity",
        "Tata saavutusta ei ole olemassa II",
        "That wasn't an eternity",
        "Infinite Time",
        "The swarm",
        "Do you really need a guide for this?",
        "We COULD afford 9",
    ],
    [
        "Yo dawg, I heard you liked infinities...",
        "Never again",
        "Eternities are the new infinity",
        "You're a mistake",
        "I wish I had gotten 7 eternities",
        "Do I really need to infinity",
        "Costco sells Dimboosts now!",
        "IT'S OVER 9000",
    ],
    [
        "Can you get infinite IP?",
        "You're already dead.",
        "5 more eternities until the update",
        "Long lasting relationship",
        "Like feasting on a behind",
        "Popular music",
        "But I wanted another prestige layer...",
        "What do I have to do to get rid of you",
    ],
    [
        "No ethical consumption",
        "Unique snowflakes",
        "I never liked this infinity stuff anyway",
        "When will it be enough?",
        "Faster than a potato^286078",
        "I told you already, time is relative",
        "Now you're thinking with dilation!",
        "This is what I have to do to get rid of you.",
    ],
    [
        "Snap back to reality",
        "How does this work?",
        "Yo dawg, I heard you liked reskins...",
        "Is this an Interstellar reference?",
        "Are you sure these are the right way around?",
        "Perks of living",
        "Master of Reality",
        "Royal flush",
    ],
    [
        "You really didn't need it anyway",
        "Y'all got any more of them glyphs?",
        "More like 'really doesn't matter'",
        "I am speed",
        "Achievement #15983",
        "College dropout",
        "It's super effective!",
        "Bruh, are you like, inside the hole?",
    ],
    [
        "That's where you're wrong kiddo",
        "Reinstalled the game and rejoined the server",
        "Actually, super easy! Barely an inconvenience!",
        "Infinity times two",
        "Perfectly balanced",
        "Nicenice.",
        "Mr. Layer? Sorry, you're not on the list",
        "Woah, we're halfway there",
    ],
    [
        "The god is delighted",
        "Hitchhiker's Guide to Reality",
        "Cet accomplissement n'existe pas III",
        "Don't you already have two of these?",
        "The first Antihistorian",
        "Mom counted to 3",
        "This mile took a celestial",
        "Destroyer of worlds",
    ],
    [
        "Antimatter Dimensions Eternal",
        "One more time",
        "Deja vOoM",
        "You're out!",
        "Four score and seven years ago",
        "An unhealthy obsession",
        "The One with Dilated Time",
        "The End",
    ],
]

CHALLENGES = [
    [f"Complete Challenge {i + 1}" for i in range(12)],
    [f"Complete Infinity Challenge {i + 1}" for i in range(8)],
    [f"Complete Eternity Challenge {j + 1}x{i + 1}" for i in range(5) for j in range(12)],
]
print(CHALLENGES)
